### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Dieterbe**
this shows the direction I want to take this in.
aside from the fixes, the goal is basically to make diffing against the sample config in metrictank repo much easier.  Both for the template file, the default attributes, as well as the generated config.  

this will need some actual testing and bugfixes probably, but wanted to show it to open up for feedback.

since the changes are very significant, we may want to publish this as a new/different cookbook.

### CODE REVIEW

**Comment by woodsaj** [comment]
looks good dieter.  As we are going to the trouble of creating what is essentially a new cookbook, lets also get rid of the deployment specific components that do not belong in this cookbook.  

https://github.com/raintank/chef_metric_tank/blob/502fbf328640ecb5dae8e75982496378d4cde7a9/recipes/install.rb#L26-L35
https://github.com/raintank/chef_metric_tank/blob/502fbf328640ecb5dae8e75982496378d4cde7a9/recipes/install.rb#L66-L74

The metrictank cookbook should work for everyone regardless of where they are deploying it.  Setting attributes like cassandra_hosts or the instance_name belong elsewhere.

**Comment by Dieterbe** [comment]
btw I know I said earlier I wanted to just use straight up files, but then started realizing that wouldn't be a good idea for people who need to dynamically set ES/cassandra/kafka/... addresses, instance id's, etc based on other data in chef. and once you start templating you might as well template the whole thing... probably?

**Comment by woodsaj** [comment]
lets also remove
https://github.com/raintank/chef_metric_tank/blob/17a2bf2362416a1782ae5a283533be441aba272f/recipes/install.rb#L71-L79
and
https://github.com/raintank/chef_metric_tank/blob/17a2bf2362416a1782ae5a283533be441aba272f/attributes/default.rb#L4-L5

this logic does not belong here and makes testing difficult. Setting the broker addresses in the node attribute should be handled outside of this cookbook.

**Comment by woodsaj** [comment]
@Dieterbe i have created 2 roleCookbooks to use this new "metrictank" cookbook.  These new roleCookbooks have been tested with testKitchen to ensure they work and also this metrictank cookbook works.  All looks good to me.

**Pull request merged**
